### ISSUE TITLE
Unable to setup pipeline deploy.sh

### ISSUE THREAD

**Issue by ketaanhshah** [Azure-Samples/modern-data-warehouse-dataops#109]
Hi All,
I am trying to install the e2e sample and I am just at the step after cloning the repo to local and running deploy.sh which creates the DevOps repo adn pipelines but I am not able to run deploy.sh. Following is the error I get (I am running Windows 10 and have Ubuntu app installed to run the bash):
![eeee](https://user-images.githubusercontent.com/12475114/105570943-469a9200-5d1a-11eb-9547-2d0d2f97b0d0.PNG)

Any help on this? I am not even able to get to the basic steps yet. Appreciate your help.

Thank you

**Comment by ketaanhshah** [comment]
Nevermind had to use dos2unix to convert the files in scripts folder as they are not on unix/linux box or on WSL.

**Comment by mdrakiburrahman** [comment]
Ran into the same error on Windows 10, even while using the docker dev container. Thanks to @ketaanhshah's tip, this quick script converted all the `.sh` files:

Added the following to `Dockerfile` to install `dos2unix`:
```bash
# Install dos2unix
RUN apt-get update \
    && apt-get -y install dos2unix
```
Then ran this from terminal:
```bash
dos2unix deploy.sh
cd scripts
for f in *.sh; do
	dos2unix $f
done
```
running `./deploy.sh` worked fine in deploying the environments after that.
