### ISSUE TITLE
Access to Public Repo (release pipeline) is denied

### ISSUE THREAD

**Issue by ketaanhshah** [Azure-Samples/modern-data-warehouse-dataops#110]
Hello,
I am trying to look at the release pipeline here: https://dev.azure.com/devlacepub/DataDevOps/_release
but I am getting access denied, I can view the build pipeline and the source code but not the Release pipeline. Can someone please give me READ access as I want to view the Release pipeline since I am struggling to get the deployment done on my end due to lot of errors (Like azure storage account name and key not getting set as Environment variable and all other cli commands fail). Can someone help with Read access to the Release pipeline?

Following is the error on Azure Storage account that I get during ADLS Gen2 creation:
![eeee](https://user-images.githubusercontent.com/12475114/105610109-d0c71280-5d7b-11eb-808d-2df186c0cacf.PNG)

Thank you

**Comment by ketaanhshah** [comment]
I have fixed the Azure Storage account error/issue above by modifying the deploy_infrastructure.sh with following:-az storage container create --name $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT

echo "Creating folders within the file system."
# Create folders for databricks libs
az storage fs directory create -n '/sys/databricks/libs' -f $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT
# Create folders for SQL external tables
az storage fs directory create -n '/data/dw/fact_parking' -f $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT
az storage fs directory create -n '/data/dw/dim_st_marker' -f $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT
az storage fs directory create -n '/data/dw/dim_parking_bay' -f $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT
az storage fs directory create -n '/data/dw/dim_location' -f $storage_file_system --account-name $AZURE_STORAGE_ACCOUNT

echo "Uploading seed data to data/seed"
az storage blob upload --account-name $AZURE_STORAGE_ACCOUNT --container-name $storage_file_system\
    --file data/seed/dim_date.csv --name "data/seed/dim_date/dim_date.csv"
az storage blob upload --account-name $AZURE_STORAGE_ACCOUNT --container-name $storage_file_system \
    --file data/seed/dim_time.csv --name "data/seed/dim_time/dim_time.csv"

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Now I am getting Keyvault error as incorrect usage
![eeee](https://user-images.githubusercontent.com/12475114/105611834-c578e480-5d85-11eb-8cdb-3fd4bd1c5361.PNG)

**Comment by devlace** [comment]
@ketaanhshah What version of az cli are you using? Can you print output of `az -v`

**Comment by ketaanhshah** [comment]
@devlace Thank you for your response. Following is the output from AZ -V:

C:\WINDOWS\system32>az -v
azure-cli                         2.12.1 *

core                              2.12.1 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
interactive                        0.4.4

**Comment by ketaanhshah** [comment]
hi @devlace can I get access to view the RELEASE pipeline from the Github project? the documentation says we can view the Build and Release pipeline but unfortunately the Release pipeline is not open for access, can you help? The reason I want to look at the Release pipeline is to view how the provisioning of the Infra components is done.

https://dev.azure.com/devlacepub/DataDevOps/_release

**Comment by devlace** [comment]
Those links were a temporary solution while the Release Pipelines were still built using the older "visual editor" and are now outdated. The Release pipelines have since been rebuilt in YAML, so you can deploy the release pipelines in your own Azure DevOps project. The sample's deployment script should deploy everything including the Build and Release Pipelines to an Azure Sub + Azure DevOps subscription of your choice.

I've linked an issue to remove the old links from the docs.

**Comment by devlace** [comment]
I'm now looking into the issue around the deployment related to the KeyVault error.

**Comment by ketaanhshah** [comment]
Thank you @devlace appreciate it, will look into the YAML files for guide on ADF deployment (infrastructure creation), do you know if there is a Json (ARM template) for Azure Synapse, Azure Databricks and Azure Data Factory deployment somewhere? I know I can always build it from Azure portal and export it as a template but I was looking for ARM template as guide (I came across this project in github from Microsoft but unforunately the infrastructure component creation is done using powershell instead of ARM template).   https://github.com/kunal333/e2esynapsedemo

**Comment by devlace** [comment]
ARM template are all here: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/master/e2e_samples/parking_sensors/infrastructure/azuredeploy.json

Though that is the just the base infrastructure. Further configuration that cannot be done in ARM is done in bash. See here. https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/master/e2e_samples/parking_sensors/scripts/deploy_infrastructure.sh

**Comment by ketaanhshah** [comment]
Thank you @devlace appreciate it.
