### ISSUE TITLE
As a developer I want to be able to run the project with minimum setup (time/cost)

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#158]
As a developer I want to be able to run the project with minimum setup (time/cost)

# Acceptance criteria 
* All required software and VS code extensions are installed and configured in the Dev container

# Definition of done
* Dockerfile and required configuration files are available for developers to consume.
* Update documentation (read-me)

**Comment by ankurokok** [comment]
Potential spike to investigate whether we can use Codespaces to simplify use / deployment

**Comment by jsburckhardt** [comment]
Quick requet for tools
- [shellcheck](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck)
- [Markdown](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
- [Code Spell Check](https://github.com/streetsidesoftware/vscode-spell-checker)
- [Azure Resource Manager (ARM) Tools](https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools)
