### ISSUE TITLE
As a developer I want to make sure that I am leveraging the linter applied on the master branch to cleanse my code.

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#159]
As a developer I want to make sure that I am leveraging the linter applied on the master branch to cleanse my code.

**Comment by ankurokok** [comment]
@devlace to comment on which linter we'll be using

**Comment by devlace** [comment]
Linter used: https://github.com/tcort/markdown-link-check
Github action that does the linter: https://github.com/gaurav-nelson/github-action-markdown-link-check
Github workflow: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/master/.github/workflows/documentation.yml
