### ISSUE TITLE
`standardize.py` does not have column `loaded_on` converted to timestamp type, load fails in `02_standardize` notebook

### ISSUE THREAD

**Issue by mdrakiburrahman** [Azure-Samples/modern-data-warehouse-dataops#162]
The line `t_parkingbay_sdf, t_parkingbay_malformed_sdf = s.standardize_parking_bay(parkingbay_sdf, load_id, loaded_on)` fails with the following during the append into `interim.parking_bay` table:

![image](https://user-images.githubusercontent.com/46581776/110221365-f4f93180-7e99-11eb-9d60-a969a0ef2a6c.png)

Error:
```
AnalysisException: Cannot write incompatible data to table '`interim`.`parking_bay`':
- Cannot safely cast 'loaded_on': string to timestamp;
```

I noticed in `standardize.py`  > `standardize_parking_bay` and `standardize_sensordata` functions:
![image](https://user-images.githubusercontent.com/46581776/110221619-3c33f200-7e9b-11eb-97c7-e337c40c6467.png)

`lit(loaded_on.isoformat()).alias("loaded_on")` is generating a string, which is probably why the append into the Parquet table fails, since it's expecting a `timestamp`:
![image](https://user-images.githubusercontent.com/46581776/110221542-ba43c900-7e9a-11eb-8b13-5a155af4c5a3.png)

> Not sure how this ever worked before, I see the `standardize.py` file hasn't changed since December 5, 2019 😕
---
## Possible fix - FYI
I changed both instances to `lit(loaded_on.isoformat()).cast("timestamp").alias("loaded_on")` in my own environment to fix the issue:
![image](https://user-images.githubusercontent.com/46581776/110222060-acdc0e00-7e9d-11eb-85c1-319c866c0f50.png)

Also, along the way, had to change `.withColumn("last_edit", to_timestamp("last_edit", "YYYYMMddHHmmss"))` to `.withColumn("last_edit", col("last_edit").cast("timestamp"))`, it seems Spark 3.0 no longer supports `YYYYMMddHHmmss` pattern for typecasting `to_timestamp` (according to the error message at least):
![image](https://user-images.githubusercontent.com/46581776/110222136-11976880-7e9e-11eb-8d30-1270560e2f19.png)

I didn't want to dig too much into the syntax, `cast("timestamp")` did the trick.

Then finally, the job succeeded:
![image](https://user-images.githubusercontent.com/46581776/110222355-9fc01e80-7e9f-11eb-8999-0f422a2fabb1.png)

**Comment by devlace** [comment]
This is fixed by this PR: https://github.com/Azure-Samples/modern-data-warehouse-dataops/pull/322
