### ISSUE TITLE
Move project_lumus folder to Azure DevOps repository (create a new project_lumus repo or Onenote)

### ISSUE THREAD

**Issue by xinsnake** [Azure-Samples/modern-data-warehouse-dataops#177]

**Comment by namitms** [comment]
Decision was made to capture the ADRs in Quokka [Onenote](https://microsoft.sharepoint.com/teams/CSEFTEFY19/_layouts/OneNote.aspx?id=%2Fteams%2FCSEFTEFY19%2FShared%20Documents%2FCrew%20-%20Quokka%2FTeam%20Quokka&wd=target%28Product%20and%20Practise%20Contributions.one%7C406AD8E6-4EE8-458D-9B7D-07F1A161B8CD%2FModern%20Data%20Warehouse%7C94D4127C-B03D-4669-A1C4-F9844C12DE70%2F%29) and add link to the same in the issues
