### ISSUE TITLE
[Bug] When running destroy.sh and some of the steps failed, the console message says "Successfully deleted xxx"

### ISSUE THREAD

**Issue by tomomi-code** [Azure-Samples/modern-data-warehouse-dataops#195]
This is the error that @tomomi-code encountered. When I didn't run `az login` but run the `destroy.sh` the console message says "Successfully deleted xxx" but it's not deleted because of the error.

![image](https://user-images.githubusercontent.com/53926778/111420176-db2fd800-873e-11eb-929b-1c756f7ec571.png)

So we need error handling in `destroy.sh`

**Comment by Azadehkhojandi** [comment]
After discussion, we agreed on destroy script should have two options
1- Delete the whole resource group
2- Delete the resources under the resource group, if the resource doesn't exist, move on to the next resource
