### ISSUE TITLE
[Bug] The NSG is not idempotent so the deployment failed if you deploy the ARM template twice

### ISSUE THREAD

**Issue by tomomi-code** [Azure-Samples/modern-data-warehouse-dataops#196]
When I run the `deploy.sh` twice, only the Network security group failed because seems like it's not idempotent.

Error Log:
```
Logged in as "xxxx@microsoft.com", set the active subscription to "xxxxxxxxxxxx"
Resource group lumos exists in australiaeast.
Validating parameters for Network Security Group...
Network Security Group parameters are valid.
Validating parameters for Virtual Network...
Virtual Network parameters are valid.
Validating parameters for Azure Databricks...
Azure Databricks parameters are valid.
Validating parameters for Azure Key Vault...
Azure Key Vault parameters are valid.
Validating parameters for Azure Storage Account...
Azure Storage Account parameters are valid.
Deploying Network Security Group...
ERROR: Deployment failed. Correlation ID: 414bae5e-a0fb-445c-bd91-ec8fcc8162bb. {
  "error": {
    "code": "ConflictWithNetworkIntentPolicy",
    "message": "Found conflicts with NetworkIntentPolicy. Details: Network Security Group cannot have resources which conflict with its subnets' network
```

**Comment by tomomi-code** [comment]
I sent CSE feedback for this bug because looks like it's still an open bug.
https://csefy19.visualstudio.com/CSEng/_workitems/edit/437511

**Comment by tomomi-code** [comment]
We can solve the issue by putting all nsg rules created by ADB automatically in nsg ARM template. But there are pros/cons
- Pros: We can solve the issue
- Cons: If ADB changed the default network rule, we have to update them manually
@devlace will decide which approach is better for this project.

**Comment by devlace** [comment]
It looks like the NSG rules don't change much (only once after SCC was released), so happy to go with the hardcoding if that helps with the east of fevelopment of the sample. Then we can revisit this if say we get unlucky and Databricks updates the NSG rules in the near future :)
