### ISSUE TITLE
Discuss and agree what infra we use

### ISSUE THREAD

**Issue by NT-D** [Azure-Samples/modern-data-warehouse-dataops#242]
# What we agreed
- Data Factory: Data processing
- ADLS Gen2: Delta Lake
- Databricks: read data from Delta Lake
- Key Vault
- Azure SQL Server

# Discussion topics
- [x] What source do we use (ex. Azure SQL DB, Cosmos DB)
<= Because this is reusable and RDBMS is popular for both Data scientist and Engineer

Requirements
- Can demo transactional process

**Comment by akirakakar** [comment]
This is completed as we completed the discussion.
