### ISSUE TITLE
Firewall deployment fails intermittently

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#246]
Firewall deployment fails intermittently

**Comment by namitms** [comment]
![image](https://user-images.githubusercontent.com/68831618/113858037-98fe3180-97e6-11eb-99f7-1aa89a9d37ef.png)

**Comment by namitms** [comment]
An azure support ticket has been created to resolve this

**Comment by namitms** [comment]
![image](https://user-images.githubusercontent.com/68831618/113959639-95aa8a80-9866-11eb-8a41-976c93803358.png)

**Comment by jsburckhardt** [comment]
Intermittent issue, it is now resolved
