### ISSUE TITLE
AzureSQL: Show how to integrate KeyVault with pipelines

### ISSUE THREAD

**Issue by devlace** [Azure-Samples/modern-data-warehouse-dataops#30]
Create a sample pipelines which stores secrets in KeyVault, ideally demonstrating deploying across environments.

**Comment by hannesne** [comment]
Can probably use this task to set and retrieve secrets from keyvault: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops

**Comment by hannesne** [comment]
Should we perhaps look at adding keyvault support to this sample? https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/master/single_tech_samples/azuresql Currently the sql database password is stored as a pipeline variable. We can change that to get the password out of keyvault. Thoughts?

**Comment by devlace** [comment]
Yeah, I was thinking we can potentially this to the fourth pipeline: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/master/single_tech_samples/azuresql/pipelines/azure-pipelines-04-multi-stage-predeploy-test.yml

That way we can keep the first three pipelines simple and easy to understand, but for a more 'production like' pipelines, we can use the fourth demonstrate this. 

I usually use AzDevOps Variables Groups that are Linked to KeyVault. An issue I've found when I quickly looked into this is that there doesn't seem to be any easy way to **automate** the deployment of linked variable groups with keyvault --- that is, you have to manually create them in the AzDevOps portal. Preferably all the samples pipelines and associated resources gets deployed in the deploy script: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/master/single_tech_samples/azuresql/deploy.sh
