### ISSUE TITLE
Add update/details to Azure Data Factory STS

### ISSUE THREAD

**Issue by jmostella** [Azure-Samples/modern-data-warehouse-dataops#320]
## Problem Statement

When working from the `Azure Data Factory` single tech sample, we found a few things we wanted to adjust from the reference architecture and workflow presented [here](https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/master/single_tech_samples/datafactory#continuous-integration-and-continuous-delivery): 

1. We actually didn't utilize __Dev__, __Staging__, and __Prod__ env. since the data was being consumed by a model training process offline. So we skipped __Prod__ for our implementation.
1. When onboarding new devs, we had a little trouble explaining _where_ the `publish` operation happens.
1. We would like to make it clear, that the output of `publish` are `Azure Resource Manager templates`, pushed to the `adf_publish` (__Publish branch__) branch.
1. We needed to see details related to how `Linked services` are set up to point to `Azure Key Vault Secrets`.
1. Also I think it needs to be clarified, that the `ARM Templates` must have the Key Vault URL overridden via parameters to point to the correct Key Vault per environment (which will in turn contain the same secrets pointing to different resources.)

## Proposed Solution

- I think we can just expand on the sections related to pipeline development workflow.
- The main diagram can omit names for environment names, and just emphasize that there is a separate environment for pipeline development and destination.
- Add section which explains the interaction between key vault,  linked services, and ARM Deployment.

## Alternative Proposals

-

## Additional Context

-

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by devlace** [comment]
Closing as we have archived this specific sample of ADF
