### ISSUE TITLE
dataset_versioning 

### ISSUE THREAD

**Issue by abnerzhangxinbinappen** [Azure-Samples/modern-data-warehouse-dataops#380]
when I run modern-data-warehouse-dataops/e2e_samples/dataset_versioning/infra$ ./setup.sh
with input:
Enter value: rg-terraformzxb stterraformzxb kv-terraformzxb eastus2

Creating 'rg-terraformzxb' resource group.
Creating 'stterraformzxb' storage account.
Creating 'kv-terraformzxb' keyvault.
Storing tf state storage key to keyvault.
Creating service principal scoped to 'rg-terraformzxb' resource group.
/resourceGroups/rg-terraformzxb'role assignment under scope '/subscriptions/37964c62-4257-45db-a9dc-92b15e36d97d
WARNING:   Role assignment creation failed.

' not found. Check the spelling and casing and try again.

how to fix this?

**Comment by devlace** [comment]
Closing as this sample is now archived
