### ISSUE TITLE
CD: Create AzureDevOps job template to deploy SQL Serverless Artifacts

### ISSUE THREAD

**Issue by devlace** [Azure-Samples/modern-data-warehouse-dataops#400]
## Description
- This is part of the **CD pipeline**
- Create AzureDevOps job template to deploy SQL Serverless Artifacts

### TODO: 
- ~~need to verify how this was done in the engagement. ~~ Serverless tables were not updated as part of the CD pipelines.
- Do we deploy: Table schema? SQL Scripts? Notebooks? etc
- Investigate whether to fine tune security permission with specific Synapse roles

Suggestion:
- Could just use External Views for now. 
- Put in known limitations. 

## DoD
- [ ] Document potential options for implementation.

**Comment by devlace** [comment]
Need to investigate to option on how to do CD with SQL Serverless Artifacts and which options to continually update the Stored Procs, Tables, etc.

**Comment by immsgbb** [comment]
Can I contribute to this task.

**Comment by devlace** [comment]
@immsgbb Yes, contributions are welcome! :)
