### ISSUE TITLE
Parking Sensors: Convert Release Pipelines to YAML format

### ISSUE THREAD

**Issue by devlace** [Azure-Samples/modern-data-warehouse-dataops#48]
Currently, Release Pipelines are built using the visual (classic) editor and much harder to include in an automated deployment script. Need to convert this to YAML.

**Comment by victordelangel84** [comment]
Where could be found the public version of the release pipeline to work on that?

**Comment by devlace** [comment]
HI @victordelangel84 , I've just completed converting all the Build and Release pipelines into YAML. You can view them here: https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/master/e2e_samples/parking_sensors/devops
