### ISSUE TITLE
Issue with databrick creation

### ISSUE THREAD

**Issue by luchua-bc** [Azure-Samples/modern-data-warehouse-dataops#480]
## Description

- A clear and concise description of what the bug is
The following code snippet in <code>deploy_infrastructure.sh</code> throws an error:
```
# Use AAD token to generate PAT token
databricks_token=$(DATABRICKS_TOKEN=$databricks_aad_token \
    DATABRICKS_HOST=$databricks_host \
    bash -c "databricks tokens create --comment 'deployment'" | jq -r .token_value)
```

The error is:
```
++ DATABRICKS_HOST=https://adb-<id>.19.azuredatabricks.net
++ bash -c 'databricks tokens create --comment '\''deployment'\'''
parse error: Invalid numeric literal at line 1, column 6
+ databricks_token=
```

## Expected Behavior

- A clear and concise description of what you expected to happen.
The databricks token is created for subsequent steps.

## Reproduce

Run <code>deploy.sh</code> and it stopped at the step described above.

I'm deploying using Docker Desktop set up through VS Code.

I also want to mention that when I access the Databricks workspace directly at <code>https://my-id.azuredatabricks.net</code>, I got the error:
```
The workspace you are trying to access does not exist in this Azure region, or your account <email>@gmail.com does not belong to any Databricks workspace in the region. Please ask your administrator to [add you as a user](https://docs.microsoft.com/azure/databricks/administration-guide/users-groups/users), or click [here](https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=https%3A%2F%2Fadb-<id>.azuredatabricks.net/login.html) to logout of Azure Active Directory and login with a different user.
```
However, I can log in through the "Launch Workspace" link in generated resource group from Azure portal.

Please help to address the issue or let me know what could be wrong.  Thanks.

**Comment by luchua-bc** [comment]
And one more note for the step before this step with error:
```
databricks_aad_token=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --output json | jq -r .accessToken) # Databricks app global id
```

The generated AAD token is a base64 encoded JWT token. However, there is no name-value pair for "accessToken". I don't quite understand what this means but hope it helps.

**Comment by luchua-bc** [comment]
A quick update. I found a work-around. I need to create a PAT (Personal Access Token) in user settings of Databricks workspace then run the following command to configure databricks session then run `deploy.sh` again:
```
/usr/local/bin/databricks configure --token
```

**Comment by devlace** [comment]
I've just tried deploying with the devcontainer, and I can't reproduce this. I appreciate that this is a few months old and we've made minor tweaks since, so might be worth doing a rebuild without cache of the devcontainer and trying again.
