### ISSUE TITLE
./deploy.sh throws unbound variable error

### ISSUE THREAD

**Issue by AraiYuno** [Azure-Samples/modern-data-warehouse-dataops#482]
## Description
![image](https://user-images.githubusercontent.com/28745975/160263727-bc63aac2-d831-49b7-b5f8-a7d6ccaecea5.png)
Tried both .devcontainer and normal route on parking_sensors e2e project.

## Expected Behavior
It should start the deployment process

## Reproduce

1. Fork the repo
2. Clone
3. Update the .envtemplate variables
4. Go to parking_sensors root folder and run `./deploy.sh`

**Comment by devlace** [comment]
@AraiYuno The error tells me that the GITHUB_REPO environment variable is not set. You need to either set this manually (ei. `export GITHUB_REPO=XXX`). 

If using the devcontainer, you need to create a `devcontainer.env` based on the `.envtemplate`, then start the devcontainer. Do not modify the .envtemplate file directly. See this for more info: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/main/e2e_samples/parking_sensors/docs/devcontainer.md.
