### ISSUE TITLE
CDDP: README.md

### ISSUE THREAD

**Issue by gary918** [Azure-Samples/modern-data-warehouse-dataops#512]
Content:
- Directory structure
- Dev environment setup
- How to test
- How to deploy
- How to run

**Comment by buhongw7583c** [comment]
Aug1 update: first part readme document, including the solution overview architecture and the local development/testing guidelines have been submitted. 

TO DO: 

- [ ] The guides for deployment on Databricks;
- [ ] better to have: video for step by step guides.
