### ISSUE TITLE
CDDP: Logging

### ISSUE THREAD

**Issue by gary918** [Azure-Samples/modern-data-warehouse-dataops#516]
(Thurston)

**Comment by thurstonchen** [comment]
UPDATES:
- Tested the _config_driven_data_pipelines_ wheel file in Databricks.
  ![image](https://user-images.githubusercontent.com/17846095/180805841-d62cbb7d-6a8e-4175-be7f-8cf9f822a602.png)

- Confirms that the logging features works fine as expected.
  ![image](https://user-images.githubusercontent.com/17846095/180806026-ba36ed74-cef5-4ad9-8940-2de30b26b95e.png)

@gary918, what else shall we check? Shall we could close this task? Thanks for your confirmation. :-)
