### ISSUE TITLE
Automated ADF Publish for Parking Sensors Demo

### ISSUE THREAD

**Issue by msha1026** [Azure-Samples/modern-data-warehouse-dataops#530]
## Problem Statement
- There is new capability to automate the ADF Publish which is a manual process at the moment in the parking sensor sample. Is there a plan to introduce this new capability into the sample? Documentation for new capability: https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-improvements#the-new-cicd-flow

## Proposed Solution
- Introduce the automation of ARM template generation for ADF in the CI pipeline. Publish as build artifact. CD Pipeline then references these artifacts instead of the `adf_publish` branch.

## Alternative Proposals
- Since manual publish to `adf_publish` branch is still supported, should a new e2e sample be made to showcase the automation of publishing ADF artifacts?

## Additional Context
- My team is currently using the e2e parking sensor example as a starting point for our DataOps project. We are working to get the automation of ADF publish integrated into the CI/CD process. More than happy to contribute back to this repo once we get it working, but would like consensus on whether we should make a new directory under `e2e_samples` or replace what is already in the parking sensors sample. Since Microsoft [documentation states that both manual and automated](https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery-improvements#what-changed) will be supported, would it make sense to have a sample showcasing each scenario?

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by devlace** [comment]
We now have a single tech sample showcasing the automated publish option: https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/main/single_tech_samples/datafactory/sample2_cicd_auto_publish
