### ISSUE TITLE
Automate ACL definitions based on configuration file

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#583]
Parent #578
Dependency #579

Modify deployment script or post-deployment script to define data lake permissions based on configuration file. 

**Pre-requirements**
To implement this piece, you don't need to deploy the full sample. You can have a similar structure in a data lake and work on a bash script as showed:

![Image](https://user-images.githubusercontent.com/46519584/211609596-b64208fe-4b3f-4741-9d0b-1f3f82becc8a.png)

In this script: https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/main/single_tech_samples/synapseanalytics/sample2_synapseserverless/scripts/deploy_infrastructure.sh, you find some examples of how to add members to an AD group and how to run az commands. Refer to this link for more information: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-acl-cli

**Success criteria:**

- Deployment (or post-deployment script) using AZ CLI able to define data lake ACL permissions based on the configuration file information

**Comment by sreedhar-guda** [comment]
Changes waiting to be committed based on the Secret Vault setup:

https://github.com/Azure-Samples/modern-data-warehouse-dataops/compare/single-tech/sample2-extension...sreedhar-guda/583-update-config
