### ISSUE TITLE
New approach to deploy Python requirement file in spark pool

### ISSUE THREAD

**Issue by 04diiguyi** [Azure-Samples/modern-data-warehouse-dataops#595]
## Problem Statement

- Currently, in this repo, we use script to deploy python packages after spark pool created. We could simply use bicep to do so.

## Proposed Solution

- Use bicep to create spark pool first and then update the pool using python packages

## Alternative Proposals

-

## Additional Context

-

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by ydaponte** [comment]
Hello @04diiguyi, maybe you can help me with this issue. I don't see the possibility to deploy the Spark pool within the bicep specification: https://learn.microsoft.com/en-us/azure/templates/microsoft.databricks/workspaces?pivots=deployment-language-bicep. Could you please point me to any documentation were you've seen that is possible? Thanks in advance!

**Comment by ydaponte** [comment]
@04diiguyi, could you please reply until 29th of November, so we decide if it is feasible to work on the issue or shall we abandon it? Thanks.

**Comment by ydaponte** [comment]
I'm closing this issue as I didn't get more information. Please feel free to re-open later if you have the clarifications we asked. Thank you!
