### ISSUE TITLE
E2E Parking Sensor sample deployment failing at databricks cli command 

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#621]
## Description

- When deploying the parking sensor sample, the script fails on the creation of the databricks token command: databricks_token=$(databricks tokens create --comment 'deployment' | jq -r .token_value)

## Expected Behavior

- databricks token is successfully created and stored in the KeyVault

## Reproduce

1. Deploy the sample ./deploy.sh
2. See error

**Comment by sreedhar-guda** [comment]
Seems same as https://github.com/Azure-Samples/modern-data-warehouse-dataops/issues/630

**Comment by devlace** [comment]
Duplicate
