### ISSUE TITLE
[Single-Tech-Samples] - Prepare Purview Folder to accommodate the second upcoming sample

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#623]
Re-structure the Purview Folder to contain sample_1 and sample_2 folders and index page to make space for the upcoming Purview sample.
The current content of the Purview folder needs to be moved to sample_1 and tested e2e to make sure that no breaking changes are introduced.

**Comment by devlace** [comment]
Closing issue as we have archived this sample
