### ISSUE TITLE
[Single-Tech-Samples] - Purview - Sample 1

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#627]
Existing purview sample has been moved to **sample1_ms_purview_in_mdw** folder under the purview folder and this changes are in a branch called [**ydaponte/623-move-purview-sample-to-sample-1**](https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/ydaponte/623-move-purview-sample-to-sample-1). 

1. Could you please check if this content is still relevant? Purview had a long evolution in the meantime and we think that we might need to deprecate the sample if you confirm that the behavior driven by the sample is no longer necessary.
2. If the content is still relevant, could you please take a look to the branch and make a quick e2e test to make sure the functionality you implemented is still working as expected with the latest releases of Purview.

**Comment by devlace** [comment]
Closing issue as we have archived this sample
