### ISSUE TITLE
ADF deployment error - Need variable for repository

### ISSUE THREAD

**Issue by victordelangel84** [Azure-Samples/modern-data-warehouse-dataops#63]
in the file mdw-dataops-clone/e2e_samples/parking_sensors/devops/azure-pipelines-cd-release.yml line 16, the repository name needs to be a variable to avoid an error deploying ADF

**Comment by devlace** [comment]
Hi @victordelangel84 , I've tried multiple ways of parametrizing this. Unfortunately, it looks like you can't use template parameters as part of the resources block in an Azure Pipeline definition. You can't use variables either.

As a workaround, I'm replacing this hard-coded reference to this repo as part of the deploy.sh script:
https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/0ef42487e0550bbd5f23d18c6508e98852a73d08/e2e_samples/parking_sensors/deploy.sh#L50

In the deployment instructions, in step 2.iii, it tells you to push up these changes to your own github repo after running the deploy.sh script:

![image](https://user-images.githubusercontent.com/5771063/84611277-ae753880-af00-11ea-837e-874d0727ebd5.png)


I'm definitely open to ideas on how to make these deployment more seamless though. I'll probably highlight this extra step more (ei. a message after deploy.sh runs) as it seems to be an easy step to miss.
