### ISSUE TITLE
ADF deployment error - linkedservices path incorrect

### ISSUE THREAD

**Issue by hungodinh** [Azure-Samples/modern-data-warehouse-dataops#66]
Looks like the linked-services reference is pointing to the incorrect folder.

`
Updating Data Factory LinkedService to point to newly deployed resources (KeyVault and DataLake).
jq: error: Could not open file .tmp/adf/linkedService/Ls_KeyVault_01.json: No such file or directory
jq: error: Could not open file .tmp/adf/linkedService/Ls_AdlsGen2_01.json: No such file or directory
Deploying Data Factory artifacts.
Creating ADF LinkedService: Ls_KeyVault_01
Unsupported Media Type({"message":"The request contains an entity body but no Content-Type header. The inferred media type 'application/octet-stream' is not supported for this resource."})
`

Fixes either:

1. Update the copy command to copy everything to  `.tmp/adf/`

https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/9a015bacd9a1f6aa1e41a03bfc2ca8a3d15a8fd9/e2e_samples/parking_sensors/scripts/deploy_infrastructure.sh#L195

2. Update `adfLsDir` to point to `.tmp/linkedService` instead of `.tmp/adf/linkedService`

https://github.com/Azure-Samples/modern-data-warehouse-dataops/blob/9a015bacd9a1f6aa1e41a03bfc2ca8a3d15a8fd9/e2e_samples/parking_sensors/scripts/deploy_infrastructure.sh#L198

**Comment by devlace** [comment]
The `cp -a` already copies everything to `.tmp/adf/`. Perhaps different shell behaviour for `cp -a`.. which shell are you using?

**Comment by hungodinh** [comment]
Using ZSH/Bash on MacOS

**Comment by devlace** [comment]
I recommend using the provided .devcontainer to deploy to limit issues related to different shell behaviours: https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/master/e2e_samples/parking_sensors#software-pre-requisites-if-you-use-dev-container
