### ISSUE TITLE
Wrong Databricks Workspace URL in ADF

### ISSUE THREAD

**Issue by tejado** [Azure-Samples/modern-data-warehouse-dataops#71]
I followed the deployment steps in the README and I got a ADF Pipe with "https://australiaeast.azuredatabricks.net" as the Databricks Workspace URL. This is wrong... at least if you deploy everything with RESOURCE_GROUP_LOCATION=northeurope.

So all the databricks connections will fail in die ADF pipe due to the wrong workspace URL.

**Comment by satonaoki** [comment]
Same here.
