### ISSUE TITLE
[D3] - Extract Monitor Hub Activity Data, API results and Fabric Item Activity

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#726]
_As a Developer, I want to access monitoring hub activity data, API results and Fabric Item Activity to determine when items were last updated or run so that we can accurately score and tag stale content._

**Resources**

- Some sort of calls to items to see when these were last updated -
- [Items - List Items - REST API (Admin) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/fabric/admin/items/list-items?tabs=HTTP),   (Pay attention to continuation token)
- [Items - REST API (Core) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/fabric/core/items)
- Some sort of calls to run activity to see when these were last run (note that we might have to do this for each item - rather than fetching all executions for a time period at workspace level - like monitoring hub) - [Job Scheduler - REST API (Core) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/fabric/core/job-scheduler) - IS THERE a BETTER way?

**Acceptance Criteria:**
- [x] Implement API calls to retrieve data on item updates and executions.
- [ ] #742
- [ ] #743

**Comment by agonzalez2014** [comment]
The below notebook will accomplish getting all Items in a Tenant:

https://app.fabric.microsoft.com/groups/2194de19-ac45-4d2c-82f1-b1eaf833f490/synapsenotebooks/f34da60f-262f-449d-bd09-b88e87a29b79?experience=data-factory
