### ISSUE TITLE
[Fabric e2e sample] Add Terraform scripts

### ISSUE THREAD

**Issue by elenaterenzi** [Azure-Samples/modern-data-warehouse-dataops#759]
Use the newly released (public preview) Fabric Terraform provider for infra deployment

DoD: 
- Utilize Fabric TF provider to deploy sample

**Comment by naga-nandyala** [comment]
I have reviewed the PR. All suggested comments were addressed.
I have also used the README and the Fabric E2E sample to test below scenarios. I was successful in deploying Azure and Fabric resources/artifacts.

1. using service principal.
2. using managed identity (virtual machine).


Using Service Principal:
![Image](https://github.com/user-attachments/assets/ab0b8d7e-9510-4a1a-92a3-445f6fa5e2dd)

Using Managed Identity:
![Image](https://github.com/user-attachments/assets/6fbd32dd-7271-4d74-ae28-e24f430ac59f)
