### ISSUE TITLE
Create CI/CD overview diagram

### ISSUE THREAD

**Issue by devlace** [Azure-Samples/modern-data-warehouse-dataops#790]
DoD:
- Document the entire CI/CD process in a diagram similar to Parking Sensor.
- CI/CD process diagram is added to README.
- Drawio format included.

**Comment by devlace** [comment]
Current strawman is for Option 3, however everyone is expected to familiarize themselves with the https://learn.microsoft.com/en-us/fabric/cicd/manage-deployment article and we'll discuss in the PR of this issue.

**Comment by sreedhar-guda** [comment]
Related issues:
#840 - Naming conventions and setup expectations
#843 - What schemas and tables were created as part of the setup.
