### ISSUE TITLE
Investigate TF linting and testing

### ISSUE THREAD

**Issue by devlace** [Azure-Samples/modern-data-warehouse-dataops#813]
DoD:
- [ ] Decision on how to improve quality and testing of our TF deployment.

**Comment by devlace** [comment]
Completed TF linting in the feature branch already. Now just finishing Testing.

**Comment by naga-nandyala** [comment]
Regarding IaC testing (terraform testing), below 2 frameworks were explored.
1. Terratest (Go Lang)
2. Terraform native testing framework (tftest.hcl)

Code has been pushed to MDE Spike repo
https://dev.azure.com/IndustrySolutions/SolutionOpsTeam/_git/MDESpikes?path=/terraform_testing&version=GBnaga/tf_testing

**Comment by devlace** [comment]
Surpassed: #891
