### ISSUE TITLE
Create Fabric notebook for setup steps

### ISSUE THREAD

**Issue by sreedhar-guda** [Azure-Samples/modern-data-warehouse-dataops#843]
Create Fabric notebook for setup steps using existing Databricks notebook as a reference.

DoD:
- Fabric notebook with all the setup steps required for parking sensor. This includes:
  - Datalake house
  - Schemas
  - Tables

Related to #842 

Implemented in #862

**Comment by sreedhar-guda** [comment]
- Created notebook for setup activity. This is a full working example with all the steps: inputs params, mounting, OTEL logging and fully implemented code functions to create schemas and tables.
- Created notebooks for Standardization and Transform steps. These are similar to Setup notebook - but the code functions are right now dummy, while rest of it like params, OTEL implementation is all set. Once ready, developers can fill that portion and rest of the portion/s need not be updated.
- Added datapipeline with all notebooks, The pipeline is coded to support high concurrency executions if the feature is enabled at workspace level for data pipelines. This would be equiavalent to using %run_multiple to call notebooks using another notebook. All notebooks are also re-written to support high concurrency executions.

**Comment by promisinganuj** [comment]
This has been completed
