### ISSUE TITLE
Change Confidential Compute reference

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#885]
As part of the Databricks cluster deployment, a Confidential Compute SKU is given in the examples. To avoid an overload of this SKU, we should refer to a more generic SKU.

**DoD**
- Modify the SKU used on the cluster json definition
- Modify read me to clearly explain which combination of SKUs needs to be checked as a pre-requirement (SKU available in the subscription/region and available on the databricks service)
- Add validation to the databricks cluster deployment to verify the capacity exists in the region before attempting to deploy.

**Comment by bsherwin** [comment]
Would it be possible to get the cluster types from the API and pass to shell script?

https://docs.databricks.com/api/workspace/clusters/listnodetypes
