### ISSUE TITLE
Upgrading bicep templates

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#886]
During the deployment, there are several BICEP warnings that alert to changes on the bicep specifications and that there are newer versions.

**DoD**
- Review all bicep modules from the sample and upgrade to the newest version
- Test e2e sample to verify that there is no breaking change
- Create a table in the ReadMe specifying what is the current version per each bicep module and in which date was upgraded in the sample

**Comment by thesqlpro** [comment]
Rafaat to review first set 6 templates
Ayman to review second set of 6 templates
