### ISSUE TITLE
Load testing script that can generate a mixture of good/bad values

### ISSUE THREAD

**Issue by DavidBurela** [Azure-Samples/modern-data-warehouse-dataops#89]
Use IoT [Telemetry Simulator](https://github.com/Azure-Samples/Iot-Telemetry-Simulator) and create a script that will generate a mixture of good/bad data.

The testing mixture should allow the pipeline stages to be worked at different ratios.

Ratio:
- 50% filtered out `deviceId >= 1,000`
- 40% "good" data `deviceId <1,000 AND temperature <100`
- 10% "bad" data `deviceId <1,000 AND temperature >=100`

**Comment by jmostella** [comment]
__Update__

Ratio:

50% filtered out deviceId >= 1,000
40% "good" data deviceId < 1,000 AND temperature <100
10% "bad" data deviceId <1,000 AND temperature >= 100

cc @shervyna
