### ISSUE TITLE
Review GitHub Enterprise /environment deployments guidance

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#898]
As per the ReadMe guidance, the GitHub Enterprise flag should be used when integrating with GitHub. For this particular configuration the AzDo organization needs to be in the same tenant as Azure. So the guidance needs to be updated to reflect:
1 - If you use GitHub Enterprise checkbox - then AzDo needs to be on the same tenant as Azure so the deployment doesn't fail
2 - If you don't use the GitHub Enterprise checkbox - then AzDo and Azure can leave on different tenants

**DoD**
- Correct ReadMe to reflect the above information

**Comment by LiliamLeme** [comment]
Information was already there in the readme and I missed. I made the changes in our setup as we discussed in ou last parkinglot @ydaponte

**Comment by ydaponte** [comment]
Closing the issue with no work attached as the guidance was already in the ReadMe.
