### ISSUE TITLE
AzFunction: Sensor filter based on include-list

### ISSUE THREAD

**Issue by DavidBurela** [Azure-Samples/modern-data-warehouse-dataops#90]
Simple Azure Function that will:

- Read from EventHub ingress
- Filter out messages where sensorId > 1,000
- Send output to Eventhub filteredSensors

**Comment by jmostella** [comment]
Hardcoded? Where does the include list come from?

**Comment by DavidBurela** [comment]
Hardcoded. `where sensorId > 1,000`
