### ISSUE TITLE
Investigate change Azdo pipelines connection to workload identity

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#903]
There is a new recommended method to create service connections in AzDO, called workload identities.

**DoD**
- Investigate and document what are the workload identities and what would be the complexity of the implementation
- Create another issue to scope the implementation

**Comment by elenaterenzi** [comment]
results of investigation:

- Pros: 
	- acts like a MSI
	- can be set up by user who is OWNER of a RG

- Cons:
	- the user who creates the devops pipeline needs to be OWNER to the resource group
	- to delete service connection you need to delete service federated credentials first

how to create:
`az devops service-endpoint create --service-endpoint-configuration ./devops.json --org https://dev.azure.com/<yourOrg> -p <yourProj>`

```json
{
    "data": {
      "subscriptionId": "<sub-id>",
      "subscriptionName": "<sub-name>",
      "creationMode": "Automatic",
      "environment": "AzureCloud",
      "scopeLevel": "Subscription"
    },
    "name": "<sc-name>",
    "type": "azurerm",
    "url": "https://management.azure.com/",
    "authorization": {
      "scheme": "WorkloadIdentityFederation",
      "parameters": {
        "tenantid": "<tenant-id>",
        "scope": "/subscriptions/<sub-id>/resourcegroups/<rg-name>" 
      }
    },
    "isShared": false,
    "isReady": true,
    "serviceEndpointProjectReferences": [
        {
          "description": "",
          "name": "<sc-name>",
          "projectReference": {
            "id": "<proj-id>",
            "name": "<proj-name>"
          }
        }
    ]
}
```
how to delete:
1) delete federated credentials
1.1) get app id of service connection credential
`spnAppObjId=$(az devops service-endpoint show --id <sc-id> --org https://dev.azure.com/<your-org> -p <your-proj> --query "data.appObjectId" -o tsv) # need output as text to get rid of double quotes`
1.2) get list of federated creds for appid
`spnCredlist=$(az ad app federated-credential list --id $spnAppObjId --query "[].id" -o json)`
1.3) delete federated creds
`for cred in $(echo "$spnCredlist" | jq -r '.[]'); do az ad app federated-credential delete --federated-credential-id $cred --id $spnAppObjId; done`
2) delete the sc
`az devops service-endpoint delete --id <sc-id> --org https://dev.azure.com/<your-org> -p <your-proj> -y`
